### ISSUE TITLE
QGIS crashes during the processing ....

### ISSUE THREAD

**Issue by EmanueleAcito89** [HydroLAB-UNIBAS/GFA-Geomorphic-Flood-Area#2]
Hi, after the conversion of the input ASCII formats to raster, I try to load the layers into the plugin and I try to run the process. At the end, the software GIS crashes, closing itself or returning these error:

minidump scritto a C: directory\d473c3071a.dmp.

**Comment by HydroLAB-UNIBAS** [comment]
The input files conversion is not needed because ASCII is a one of raster formats readable by QGIS. So you can use ASCII raster to run the plug-in.

**Comment by EmanueleAcito89** [comment]
The problem is the same, it crashes again. Is this version compatible with the last update og QGIS 2,18,16? Thanks!

**Comment by HydroLAB-UNIBAS** [comment]
The tool was exstensively test on QGIS 2.14. However, we have made tests also on 2.8 and 2.18 with successfull outcomes. Minudump error is quite generic and it could be due to many issues. I would invite you to send us more information to solve the opened issue according with our time availability. Thanks!

**Comment by EmanueleAcito89** [comment]
Ok, I added dr.Albano on Skype. I can communicate with him when possible.

**Comment by EmanueleAcito89** [comment]
The problem is solved. The error concerns the path of my stored data. The software crash is due to the substitution of the underscore with a space.
Thank you for the patience.
Good bye!
